version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    
    # option one:
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: peleg
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    
    # option two:
    env_file:
      - ./env/mongo.env
    container_name: mongodb
  
  backend:
    # option one:
    # image: 'goals-node'
    
    # option two:
    build: ./backend
    
    # option three:
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - '80:80'
    volumes: 
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    container_name: backend  
  
  frontend:  
    build: ./frontend
    ports:
      - '3000:3000'
    volumes: 
      - ./frontend/src:/app/src
    stdin_open: true  
    tty: true
    depends_on:
      - backend
    container_name: frontend  

# Only named volumes.
volumes:
  data:
  logs:

  
